### ISSUE TITLE
Can't get countdown timer to render properly

### ISSUE THREAD

**Issue by DagnyJay** [micahwierenga/sei-cc-7-project-4-issues#16]
_Describe the issue._
I'm getting the component to show up, but instead of showing '10:00', it says 'NaN:NaN'. I'd love to get it to display properly, and also get the onClick functionality implemented so that it starts ticking down as soon as a user clicks the Accept button.

_Paste any relevant code and/or errors (use triple backticks before and after to format as code)._
There aren't any errors, and I'm unsure of which component (or lack thereof) is responsible

_Paste links to any resources you've consulted for help._
React Mastermind GameTimer code
The lesson plan from when we built that
this tutorial, but it's not super helpful: https://codeburst.io/lets-build-a-countdown-timer-with-react-part-1-2e7d5692d914

Describe your attempt(s) at resolving the issue.
Copied code from mastermind and refactored, going through that lesson plan

**Comment by micahwierenga** [comment]
1. Inside `getInitialState`, your time is a string instead of a number. change `"10:00"` to `10`.
2. This method isn't being used to initialize state. Inside your state, include `...this.getInitialState()`.
3. Inside the `formatTime` function in your `Timer` component, you only need to pad with `'0'` (not `'10'` for both minutes and seconds.
4. In App.js, create a function called something like `handleStartClock` and have it update `isTiming` with either `true` or, if you want to allow the Accept button to pause the timer, use `!this.state.isTiming` so that, whenever it's clicked, it just sets `isTiming` to either true or false. After you've created this function, pass it down so that you can use it with the `onClick` event on your Accept button.
