### ISSUE TITLE
Can't figure out how to update page with stuff from database on submit

### ISSUE THREAD

**Issue by CodyLHart** [micahwierenga/sei-cc-7-project-4-issues#5]
`handleSubmit = async (e) => {
        e.preventDefault();
        try {
            await adminService.createProductType(this.state);
            this.setState({productType: ''});
            this.props.history.push('/');
        } catch (err) {
            alert('error');
        }
    }`

**Comment by micahwierenga** [comment]
For the productType issue, there was no response from the back-end, causing an error when the front-end fetch request was attempting to parse json.

For the product issue, we discovered that enum and ObjectId configs resulted in a required field, so that the product was being rejected since these fields weren't defined. Also, the productType field needed to be an ObjectId instead of a string.
